Repository Comp231-S4G5/OneClickCleaner, pull requests merged in 2020-12, with the labels that each got.

#144 Cai
  Activity Diagram.jpg
  Class.png
  Client Emergency Sequence Diagram.jpg
  Client.Emergency package diagram.JPG
  Component Diagram.jpg
  Deployment diagram.jpg
  ERD.png
  OCC/.vs/OCC/v16/.suo
  OCC/OCC.sln
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/OCC/wwwroot/images/Banner-00.jpg
  OCC/OCC/wwwroot/images/Banner-01.jpg
  OCC/OCC/wwwroot/images/Banner-02.jpg
  OCC/OCC/wwwroot/images/Banner-03.jpg
  README.md
  StateDiagram1.png
  StateDiagram2.png
  StateDiagram3.png
  Us11.png
  object1.png
Labels: 1, Task

#145 Jhennifer
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Migrations/20201126045904_initial.Designer.cs
  OCC/OCC/Migrations/20201126045904_initial.cs
  OCC/OCC/Models/SeedCleaner.cs
  OCC/OCC/Views/Booking/SelectingCleaner.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Emergency/ServiceDetail.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/OCC/wwwroot/css/CleanerForm.css
  OCC/OCC/wwwroot/css/Login.css
  OCC/OCC/wwwroot/images/banner1.jpg
  OCC/OCC/wwwroot/images/banner2.jpg
  OCC/OCC/wwwroot/images/eric.JPG
  OCC/OCC/wwwroot/images/james.JPG
  OCC/OCC/wwwroot/images/mike.JPG
Labels: Task

#147 Us14
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  Activity Diagram.jpg
  Architecture Diagram.jpg
  Class.png
  Client Emergency Sequence Diagram.jpg
  Component Diagram.jpg
  Deployment diagram.jpg
  ERD.png
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC.sln
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Migrations/20201126045904_initial.Designer.cs
  OCC/OCC/Migrations/20201126045904_initial.cs
  OCC/OCC/Models/Cleaner.cs
  OCC/OCC/Models/SeedCleaner.cs
  OCC/OCC/Resources/images/main-banner.jpg
  OCC/OCC/Views/Admin/DisplayCleanerList.cshtml
  OCC/OCC/Views/Admin/Edit.cshtml
  OCC/OCC/Views/Booking/SelectingCleaner.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Emergency/CheckOut.cshtml
  OCC/OCC/Views/Emergency/NoCleanerAvailable.cshtml
  OCC/OCC/Views/Emergency/ServiceDetail.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/OCC/wwwroot/css/CleanerForm.css
  OCC/OCC/wwwroot/css/Login.css
  OCC/OCC/wwwroot/css/StyleSheet.css
  OCC/OCC/wwwroot/images/Alejandro.JPG
  OCC/OCC/wwwroot/images/Amanda.JPG
  OCC/OCC/wwwroot/images/Banner-00.jpg
  OCC/OCC/wwwroot/images/Banner-01.jpg
  OCC/OCC/wwwroot/images/Banner-02.jpg
  OCC/OCC/wwwroot/images/Banner-03.jpg
  OCC/OCC/wwwroot/images/Paola.JPG
  OCC/OCC/wwwroot/images/Prize Winner Form[fillable] 2020 _luana.pdf
  OCC/OCC/wwwroot/images/banner1.jpg
  OCC/OCC/wwwroot/images/banner2.jpg
  OCC/OCC/wwwroot/images/d374750e-0d58-47da-9624-584a7823fb23.jpg
  OCC/OCC/wwwroot/images/eric.JPG
  OCC/OCC/wwwroot/images/james.JPG
  OCC/OCC/wwwroot/images/mike.JPG
  Object14.png
  README.md
  StateDiagram1.png
  StateDiagram2.png
  StateDiagram3.png
  Us14.png
Labels: 2, Task

#148 Andrea
  .vs/OneClickCleaner/v16/.suo
  .vs/VSWorkspaceState.json
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/UsersController.cs
  OCC/OCC/Migrations/20201203032422_Initial.Designer.cs
  OCC/OCC/Migrations/20201203032422_Initial.cs
  OCC/OCC/Models/AppUser.cs
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
Labels: 2, Task

#150 Ajlan
  OCC/OCC/Controllers/AccountController.cs
Labels: 1, Task

#154 Us14
  .vs/OneClickCleaner/v16/.suo
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  Activity Diagram.jpg
  Architecture Diagram.jpg
  Class.png
  Client Emergency Sequence Diagram.jpg
  Component Diagram.jpg
  Deployment diagram.jpg
  ERD.png
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC.sln
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/BookingController.cs
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Controllers/EmergencyController.cs
  OCC/OCC/Controllers/UsersController.cs
  OCC/OCC/Migrations/20201203032422_Initial.Designer.cs
  OCC/OCC/Migrations/20201203032422_Initial.cs
  OCC/OCC/Migrations/ApplicationDbContextModelSnapshot.cs
  OCC/OCC/Models/AppUser.cs
  OCC/OCC/Models/SeedCleaner.cs
  OCC/OCC/Views/Booking/SelectingCleaner.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Emergency/CheckOut.cshtml
  OCC/OCC/Views/Emergency/NoCleanerAvailable.cshtml
  OCC/OCC/Views/Emergency/ServiceDetail.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/OCC/wwwroot/css/CleanerForm.css
  OCC/OCC/wwwroot/css/Login.css
  OCC/OCC/wwwroot/css/StyleSheet.css
  OCC/OCC/wwwroot/images/Banner-00.jpg
  OCC/OCC/wwwroot/images/Banner-01.jpg
  OCC/OCC/wwwroot/images/Banner-02.jpg
  OCC/OCC/wwwroot/images/Banner-03.jpg
  OCC/OCC/wwwroot/images/Prize Winner Form[fillable] 2020 _luana.pdf
  OCC/OCC/wwwroot/images/banner1.jpg
  OCC/OCC/wwwroot/images/banner2.jpg
  OCC/OCC/wwwroot/images/eric.JPG
  OCC/OCC/wwwroot/images/james.JPG
  OCC/OCC/wwwroot/images/mike.JPG
  Object14.png
  README.md
  StateDiagram1.png
  StateDiagram2.png
  StateDiagram3.png
  US14_package diagram_.JPG
  Us14.png
Labels: 2, Task

#156 Jorge
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Models/UserViewModels.cs
  OCC/OCC/Models/ViewModels/UserModel.cs
  OCC/OCC/Views/Admin/DisplayCleanerList.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
Labels: 2, Task

#153 Luana send to US15
  .vs/OneClickCleaner/v16/.suo
  .vs/VSWorkspaceState.json
  Client.Emergency package diagram.JPG
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/UsersController.cs
  OCC/OCC/Migrations/20201203032422_Initial.Designer.cs
  OCC/OCC/Migrations/20201203032422_Initial.cs
  OCC/OCC/Models/AppUser.cs
  OCC/OCC/Models/SeedCleaner.cs
  OCC/OCC/Views/Booking/SelectingCleaner.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Emergency/ServiceDetail.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/OCC/wwwroot/css/CleanerForm.css
  OCC/OCC/wwwroot/css/Login.css
  OCC/OCC/wwwroot/images/banner1.jpg
  OCC/OCC/wwwroot/images/banner2.jpg
  OCC/OCC/wwwroot/images/eric.JPG
  OCC/OCC/wwwroot/images/james.JPG
  OCC/OCC/wwwroot/images/mike.JPG
  README.md
  US14_package diagram_.JPG
Labels: 2, Task

#158 Andrea
  .vs/OneClickCleaner/v16/.suo
  .vs/slnx.sqlite
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/AdminController.cs
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Models/AppIdentityDbContext.cs
  OCC/OCC/Models/Cleaner.cs
  OCC/OCC/Models/EFCleanerRepository.cs
  OCC/OCC/Models/UserViewModels.cs
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
Labels: 2, Task

#166 Andrea
  .vs/OneClickCleaner/v16/.suo
  .vs/slnx.sqlite
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Migrations/20201204235401_Initial.Designer.cs
  OCC/OCC/Migrations/20201204235401_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.Designer.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/AppIdentityDbContextModelSnapshot.cs
  OCC/OCC/Migrations/ApplicationDbContextModelSnapshot.cs
  OCC/OCC/Models/ApplicationDbContext.cs
  OCC/OCC/Models/UserViewModels.cs
  OCC/OCC/Startup.cs
  OCC/OCC/Views/Account/Login.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerDetails.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/_ViewImports.cshtml
  OCC/OCC/appsettings.json
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
Labels: 2, Task

#167 Andrea
  .vs/OneClickCleaner/v16/.suo
  .vs/slnx.sqlite
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Migrations/20201204235401_Initial.Designer.cs
  OCC/OCC/Migrations/20201204235401_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.Designer.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/AppIdentityDbContextModelSnapshot.cs
  OCC/OCC/Migrations/ApplicationDbContextModelSnapshot.cs
  OCC/OCC/Models/ApplicationDbContext.cs
  OCC/OCC/Models/UserViewModels.cs
  OCC/OCC/Startup.cs
  OCC/OCC/Views/Account/Login.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerDetails.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/_ViewImports.cshtml
  OCC/OCC/appsettings.json
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
Labels: 1

#168 Us16
  .vs/OneClickCleaner/v16/.suo
  .vs/slnx.sqlite
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Migrations/20201204235401_Initial.Designer.cs
  OCC/OCC/Migrations/20201204235401_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.Designer.cs
  OCC/OCC/Migrations/AppIdentityDb/20201204235454_Initial.cs
  OCC/OCC/Migrations/AppIdentityDb/AppIdentityDbContextModelSnapshot.cs
  OCC/OCC/Migrations/ApplicationDbContextModelSnapshot.cs
  OCC/OCC/Models/ApplicationDbContext.cs
  OCC/OCC/Models/UserViewModels.cs
  OCC/OCC/Startup.cs
  OCC/OCC/Views/Account/Login.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerDetails.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/_ViewImports.cshtml
  OCC/OCC/appsettings.json
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
Labels: 1

#169 Luana
  .gitattributes
  .vs/slnx.sqlite
  OCC/OCC/Controllers/HomeController.cs
  OCC/OCC/Migrations/20201205023848_Initial.Designer.cs
  OCC/OCC/Migrations/20201205023848_Initial.cs
  OCC/OCC/Migrations/AppIdentityDbContextModelSnapshot.cs
  OCC/OCC/Migrations/ApplicationDb/20201205023909_Initial.Designer.cs
  OCC/OCC/Migrations/ApplicationDb/20201205023909_Initial.cs
  OCC/OCC/Migrations/ApplicationDb/ApplicationDbContextModelSnapshot.cs
  OCC/OCC/Views/Account/Login.cshtml
  OCC/OCC/Views/Cleaner/CleanerCheckOut.cshtml
  OCC/OCC/Views/Home/CompanyPolicy.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/Views/Home/aboutUs.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/wwwroot/css/Login.css
  OCC/OCC/wwwroot/css/StyleSheet.css
  OCC/OCC/wwwroot/images/contact.JPG
Labels: 1, Task

#170 update
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  OCC/OCC.sln
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/AdminController.cs
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Controllers/EmergencyController.cs
  OCC/OCC/Controllers/HomeController.cs
  OCC/OCC/Controllers/UsersController.cs
  OCC/OCC/Migrations/20201205200727_Initial.Designer.cs
  OCC/OCC/Migrations/20201205200727_Initial.cs
  OCC/OCC/Migrations/ApplicationDb/20201205200748_Initial.Designer.cs
  OCC/OCC/Migrations/ApplicationDb/20201205200748_Initial.cs
  OCC/OCC/Models/IdentitySeedData.cs
  OCC/OCC/Models/Order.cs
  OCC/OCC/Models/SeedCleaner.cs
  OCC/OCC/Startup.cs
  OCC/OCC/Views/Admin/DisplayCleanerList.cshtml
  OCC/OCC/Views/Booking/SelectingCleaner.cshtml
  OCC/OCC/Views/Booking/ServiceDetail.cshtml
  OCC/OCC/Views/Cleaner/CleanerCheckOut.cshtml
  OCC/OCC/Views/Cleaner/CleanerDetail.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerDetails.cshtml
  OCC/OCC/Views/Cleaner/RegisteredCleanerSignUp.cshtml
  OCC/OCC/Views/Emergency/CheckOut.cshtml
  OCC/OCC/Views/Emergency/CustomerInfo.cshtml
  OCC/OCC/Views/Emergency/ServiceDetail.cshtml
  OCC/OCC/Views/Home/CompanyPolicy.cshtml
  OCC/OCC/Views/Home/Index.cshtml
  OCC/OCC/Views/Home/aboutUs.cshtml
  OCC/OCC/Views/Shared/_Layout.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/wwwroot/css/CleanerForm.css
  OCC/OCC/wwwroot/images/Paola.JPG
  OCC/OCC/wwwroot/images/Prize Winner Form[fillable] 2020 _luana.pdf
  OCC/OCC/wwwroot/images/ambulance-emergency.png
  OCC/OCC/wwwroot/images/calendar.png
  OCC/OCC/wwwroot/images/cleaner2.png
Labels: 2

#171 Jorge
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/Controllers/AccountController.cs
  OCC/OCC/Controllers/AdminController.cs
  OCC/OCC/Controllers/BookingController.cs
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/Controllers/EmergencyController.cs
  OCC/OCC/Controllers/HomeController.cs
  OCC/OCC/Controllers/UsersController.cs
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
Labels: 1

#173 Andrea
  .vs/OneClickCleaner/v16/.suo
  .vs/slnx.sqlite
  OCC/.vs/OCC/DesignTimeBuild/.dtbcache.v2
  OCC/.vs/OCC/v16/.suo
  OCC/OCC.sln
  OCC/OCC/Controllers/CleanerController.cs
  OCC/OCC/OCC.csproj
  OCC/OCC/Views/Cleaner/RegisteredCleanerDetails.cshtml
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/OCC/obj/project.nuget.cache
  OCC/UnitTestProject1/MvcMockHelper.cs
  OCC/UnitTestProject1/Test.cs
  OCC/UnitTestProject1/UnitTestProject1.csproj
Labels: 1

#175 Jorge
  OCC/.vs/OCC/v16/.suo
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.assets.cache
  OCC/OCC/obj/Debug/netcoreapp2.1/OCC.csprojAssemblyReference.cache
  OCC/OCC/obj/OCC.csproj.nuget.dgspec.json
  OCC/OCC/obj/OCC.csproj.nuget.g.props
  OCC/OCC/obj/project.assets.json
  OCC/UnitTestProject1/Test.cs
  OCC/UnitTestProject1/UnitTestProject1.csproj
Labels: 1
